#- name: stop jboss
#  service: name={{ jboss_service_name }} state=stopped
#- name: start jboss
#  service: name={{ jboss_service_name }} state=started
- name: stop jboss
  command: /etc/init.d/jboss stop
- name: pause jboss
  pause: seconds=15 prompt="Restarting"
- name: start jboss
  command: /etc/init.d/jboss start
